name: neural_cop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  awesome_notifications: ^0.7.4+1
  flutter:
    sdk: flutter
  http: ^1.0.0
  map_launcher: ^2.5.0+1
  prompt_dialog: ^1.0.13
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/neuralcop.jpeg

flutter_launcher_icons:
  android: true
  image_path: "assets/img/neuralcop.jpeg"
  adaptive_icon_foreground: "assets/img/neuralcop.jpeg"
  adaptive_icon_background: "#1b1a1c"